// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    partial class ClaimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hospital")
                        .HasColumnType("int");

                    b.Property<int>("InsuredId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalCase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TreatingDoctor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("InsuredId");

                    b.ToTable("Claim");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdmissionDate = new DateTime(2023, 6, 28, 11, 12, 32, 476, DateTimeKind.Local).AddTicks(4801),
                            Amount = 9737m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 7, 28, 21, 47, 49, 734, DateTimeKind.Local).AddTicks(8028),
                            Hospital = 10,
                            InsuredId = 7,
                            MedicalCase = "Disease-2",
                            Remarks = "Remark-2",
                            TreatingDoctor = 3
                        },
                        new
                        {
                            Id = 2,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 45, 58, 694, DateTimeKind.Local).AddTicks(1497),
                            Amount = 4264m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 9, 20, 13, 34, 41, 942, DateTimeKind.Local).AddTicks(2912),
                            Hospital = 14,
                            InsuredId = 9,
                            MedicalCase = "Disease-3",
                            Remarks = "Remark-3",
                            TreatingDoctor = 18
                        },
                        new
                        {
                            Id = 3,
                            AdmissionDate = new DateTime(2023, 6, 28, 8, 36, 2, 983, DateTimeKind.Local).AddTicks(1216),
                            Amount = 9723m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 10, 14, 5, 0, 51, 752, DateTimeKind.Local).AddTicks(7405),
                            Hospital = 41,
                            InsuredId = 7,
                            MedicalCase = "Disease-4",
                            Remarks = "Remark-4",
                            TreatingDoctor = 19
                        },
                        new
                        {
                            Id = 4,
                            AdmissionDate = new DateTime(2023, 6, 28, 6, 58, 22, 97, DateTimeKind.Local).AddTicks(5377),
                            Amount = 675m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 5, 29, 12, 11, 16, 763, DateTimeKind.Local).AddTicks(4361),
                            Hospital = 5,
                            InsuredId = 8,
                            MedicalCase = "Disease-5",
                            Remarks = "Remark-5",
                            TreatingDoctor = 17
                        },
                        new
                        {
                            Id = 5,
                            AdmissionDate = new DateTime(2023, 6, 28, 1, 0, 33, 328, DateTimeKind.Local).AddTicks(310),
                            Amount = 2102m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 9, 20, 9, 11, 58, 147, DateTimeKind.Local).AddTicks(4052),
                            Hospital = 23,
                            InsuredId = 8,
                            MedicalCase = "Disease-6",
                            Remarks = "Remark-6",
                            TreatingDoctor = 3
                        },
                        new
                        {
                            Id = 6,
                            AdmissionDate = new DateTime(2023, 6, 28, 5, 55, 8, 752, DateTimeKind.Local).AddTicks(1262),
                            Amount = 1754m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 11, 27, 3, 56, 46, 845, DateTimeKind.Local).AddTicks(2148),
                            Hospital = 33,
                            InsuredId = 10,
                            MedicalCase = "Disease-7",
                            Remarks = "Remark-7",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 7,
                            AdmissionDate = new DateTime(2023, 6, 27, 15, 7, 7, 349, DateTimeKind.Local).AddTicks(146),
                            Amount = 2708m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 5, 24, 20, 38, 4, 644, DateTimeKind.Local).AddTicks(7465),
                            Hospital = 22,
                            InsuredId = 6,
                            MedicalCase = "Disease-8",
                            Remarks = "Remark-8",
                            TreatingDoctor = 2
                        },
                        new
                        {
                            Id = 8,
                            AdmissionDate = new DateTime(2023, 6, 27, 13, 25, 3, 362, DateTimeKind.Local).AddTicks(726),
                            Amount = 6465m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 9, 12, 18, 44, 14, 29, DateTimeKind.Local).AddTicks(7397),
                            Hospital = 23,
                            InsuredId = 7,
                            MedicalCase = "Disease-9",
                            Remarks = "Remark-9",
                            TreatingDoctor = 1
                        },
                        new
                        {
                            Id = 9,
                            AdmissionDate = new DateTime(2023, 6, 28, 1, 7, 45, 972, DateTimeKind.Local).AddTicks(612),
                            Amount = 9065m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 3, 27, 5, 45, 1, 802, DateTimeKind.Local).AddTicks(8515),
                            Hospital = 31,
                            InsuredId = 6,
                            MedicalCase = "Disease-10",
                            Remarks = "Remark-10",
                            TreatingDoctor = 1
                        },
                        new
                        {
                            Id = 10,
                            AdmissionDate = new DateTime(2023, 6, 28, 5, 52, 45, 561, DateTimeKind.Local).AddTicks(3804),
                            Amount = 1801m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 8, 21, 10, 6, 10, 437, DateTimeKind.Local).AddTicks(4871),
                            Hospital = 33,
                            InsuredId = 6,
                            MedicalCase = "Disease-11",
                            Remarks = "Remark-11",
                            TreatingDoctor = 14
                        },
                        new
                        {
                            Id = 11,
                            AdmissionDate = new DateTime(2023, 6, 28, 8, 15, 5, 796, DateTimeKind.Local).AddTicks(1220),
                            Amount = 8491m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 10, 31, 1, 11, 11, 880, DateTimeKind.Local).AddTicks(2487),
                            Hospital = 32,
                            InsuredId = 1,
                            MedicalCase = "Disease-12",
                            Remarks = "Remark-12",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 12,
                            AdmissionDate = new DateTime(2023, 6, 28, 0, 43, 58, 537, DateTimeKind.Local).AddTicks(7828),
                            Amount = 3668m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 7, 11, 10, 54, 22, 225, DateTimeKind.Local).AddTicks(7627),
                            Hospital = 31,
                            InsuredId = 10,
                            MedicalCase = "Disease-13",
                            Remarks = "Remark-13",
                            TreatingDoctor = 8
                        },
                        new
                        {
                            Id = 13,
                            AdmissionDate = new DateTime(2023, 6, 27, 18, 42, 39, 829, DateTimeKind.Local).AddTicks(3199),
                            Amount = 3357m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 5, 21, 5, 18, 43, 121, DateTimeKind.Local).AddTicks(5963),
                            Hospital = 44,
                            InsuredId = 10,
                            MedicalCase = "Disease-14",
                            Remarks = "Remark-14",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 14,
                            AdmissionDate = new DateTime(2023, 6, 28, 3, 5, 7, 338, DateTimeKind.Local).AddTicks(9247),
                            Amount = 6409m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 8, 10, 12, 51, 59, 987, DateTimeKind.Local).AddTicks(9521),
                            Hospital = 16,
                            InsuredId = 1,
                            MedicalCase = "Disease-15",
                            Remarks = "Remark-15",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 15,
                            AdmissionDate = new DateTime(2023, 6, 27, 22, 32, 31, 750, DateTimeKind.Local).AddTicks(3758),
                            Amount = 5306m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 10, 7, 15, 49, 22, 861, DateTimeKind.Local).AddTicks(1738),
                            Hospital = 7,
                            InsuredId = 8,
                            MedicalCase = "Disease-16",
                            Remarks = "Remark-16",
                            TreatingDoctor = 16
                        },
                        new
                        {
                            Id = 16,
                            AdmissionDate = new DateTime(2023, 6, 27, 21, 38, 8, 343, DateTimeKind.Local).AddTicks(9932),
                            Amount = 3378m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 12, 31, 13, 19, 3, 2, DateTimeKind.Local).AddTicks(1678),
                            Hospital = 17,
                            InsuredId = 3,
                            MedicalCase = "Disease-17",
                            Remarks = "Remark-17",
                            TreatingDoctor = 14
                        },
                        new
                        {
                            Id = 17,
                            AdmissionDate = new DateTime(2023, 6, 27, 14, 15, 54, 218, DateTimeKind.Local).AddTicks(7409),
                            Amount = 5753m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 4, 2, 11, 18, 4, 480, DateTimeKind.Local).AddTicks(4526),
                            Hospital = 43,
                            InsuredId = 6,
                            MedicalCase = "Disease-18",
                            Remarks = "Remark-18",
                            TreatingDoctor = 10
                        },
                        new
                        {
                            Id = 18,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 30, 13, 28, DateTimeKind.Local).AddTicks(3432),
                            Amount = 7075m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 5, 20, 23, 51, 4, 416, DateTimeKind.Local).AddTicks(9500),
                            Hospital = 24,
                            InsuredId = 4,
                            MedicalCase = "Disease-19",
                            Remarks = "Remark-19",
                            TreatingDoctor = 0
                        },
                        new
                        {
                            Id = 19,
                            AdmissionDate = new DateTime(2023, 6, 28, 11, 32, 43, 720, DateTimeKind.Local).AddTicks(3505),
                            Amount = 1882m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 9, 4, 5, 56, 17, 356, DateTimeKind.Local).AddTicks(9945),
                            Hospital = 15,
                            InsuredId = 1,
                            MedicalCase = "Disease-20",
                            Remarks = "Remark-20",
                            TreatingDoctor = 10
                        },
                        new
                        {
                            Id = 20,
                            AdmissionDate = new DateTime(2023, 6, 28, 5, 55, 45, 706, DateTimeKind.Local).AddTicks(5695),
                            Amount = 416m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 9, 5, 7, 47, 9, 534, DateTimeKind.Local).AddTicks(4720),
                            Hospital = 12,
                            InsuredId = 5,
                            MedicalCase = "Disease-21",
                            Remarks = "Remark-21",
                            TreatingDoctor = 2
                        },
                        new
                        {
                            Id = 21,
                            AdmissionDate = new DateTime(2023, 6, 27, 13, 55, 10, 661, DateTimeKind.Local).AddTicks(3923),
                            Amount = 8725m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 3, 10, 3, 15, 52, 154, DateTimeKind.Local).AddTicks(7609),
                            Hospital = 43,
                            InsuredId = 6,
                            MedicalCase = "Disease-22",
                            Remarks = "Remark-22",
                            TreatingDoctor = 14
                        },
                        new
                        {
                            Id = 22,
                            AdmissionDate = new DateTime(2023, 6, 27, 19, 9, 5, 769, DateTimeKind.Local).AddTicks(5361),
                            Amount = 3499m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 10, 5, 10, 3, 58, 749, DateTimeKind.Local).AddTicks(3389),
                            Hospital = 27,
                            InsuredId = 7,
                            MedicalCase = "Disease-23",
                            Remarks = "Remark-23",
                            TreatingDoctor = 8
                        },
                        new
                        {
                            Id = 23,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 19, 58, 553, DateTimeKind.Local).AddTicks(3757),
                            Amount = 2609m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 10, 2, 3, 46, 58, 600, DateTimeKind.Local).AddTicks(3969),
                            Hospital = 15,
                            InsuredId = 2,
                            MedicalCase = "Disease-24",
                            Remarks = "Remark-24",
                            TreatingDoctor = 14
                        },
                        new
                        {
                            Id = 24,
                            AdmissionDate = new DateTime(2023, 6, 28, 11, 27, 34, 867, DateTimeKind.Local).AddTicks(1290),
                            Amount = 5136m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 7, 22, 12, 5, 39, 904, DateTimeKind.Local).AddTicks(5631),
                            Hospital = 40,
                            InsuredId = 7,
                            MedicalCase = "Disease-25",
                            Remarks = "Remark-25",
                            TreatingDoctor = 3
                        },
                        new
                        {
                            Id = 25,
                            AdmissionDate = new DateTime(2023, 6, 27, 22, 31, 58, 902, DateTimeKind.Local).AddTicks(7526),
                            Amount = 460m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 4, 16, 6, 11, 0, 946, DateTimeKind.Local).AddTicks(9857),
                            Hospital = 35,
                            InsuredId = 6,
                            MedicalCase = "Disease-26",
                            Remarks = "Remark-26",
                            TreatingDoctor = 6
                        },
                        new
                        {
                            Id = 26,
                            AdmissionDate = new DateTime(2023, 6, 28, 2, 23, 57, 263, DateTimeKind.Local).AddTicks(152),
                            Amount = 314m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 7, 17, 16, 35, 58, 195, DateTimeKind.Local).AddTicks(574),
                            Hospital = 15,
                            InsuredId = 10,
                            MedicalCase = "Disease-27",
                            Remarks = "Remark-27",
                            TreatingDoctor = 11
                        },
                        new
                        {
                            Id = 27,
                            AdmissionDate = new DateTime(2023, 6, 27, 18, 18, 19, 170, DateTimeKind.Local).AddTicks(7200),
                            Amount = 683m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 5, 21, 19, 53, 16, 626, DateTimeKind.Local).AddTicks(9215),
                            Hospital = 31,
                            InsuredId = 4,
                            MedicalCase = "Disease-28",
                            Remarks = "Remark-28",
                            TreatingDoctor = 8
                        },
                        new
                        {
                            Id = 28,
                            AdmissionDate = new DateTime(2023, 6, 28, 5, 39, 29, 481, DateTimeKind.Local).AddTicks(7796),
                            Amount = 8216m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 13, 1, 33, 52, 905, DateTimeKind.Local).AddTicks(4508),
                            Hospital = 45,
                            InsuredId = 4,
                            MedicalCase = "Disease-29",
                            Remarks = "Remark-29",
                            TreatingDoctor = 16
                        },
                        new
                        {
                            Id = 29,
                            AdmissionDate = new DateTime(2023, 6, 27, 18, 18, 53, 61, DateTimeKind.Local).AddTicks(3629),
                            Amount = 9884m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 8, 2, 13, 45, 44, 667, DateTimeKind.Local).AddTicks(8495),
                            Hospital = 0,
                            InsuredId = 1,
                            MedicalCase = "Disease-30",
                            Remarks = "Remark-30",
                            TreatingDoctor = 18
                        },
                        new
                        {
                            Id = 30,
                            AdmissionDate = new DateTime(2023, 6, 27, 15, 36, 46, 833, DateTimeKind.Local).AddTicks(6555),
                            Amount = 7423m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 11, 20, 56, 2, 156, DateTimeKind.Local).AddTicks(9802),
                            Hospital = 13,
                            InsuredId = 3,
                            MedicalCase = "Disease-31",
                            Remarks = "Remark-31",
                            TreatingDoctor = 13
                        },
                        new
                        {
                            Id = 31,
                            AdmissionDate = new DateTime(2023, 6, 28, 9, 51, 44, 503, DateTimeKind.Local).AddTicks(3019),
                            Amount = 6435m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 10, 14, 22, 36, 53, 845, DateTimeKind.Local).AddTicks(3782),
                            Hospital = 6,
                            InsuredId = 6,
                            MedicalCase = "Disease-32",
                            Remarks = "Remark-32",
                            TreatingDoctor = 10
                        },
                        new
                        {
                            Id = 32,
                            AdmissionDate = new DateTime(2023, 6, 28, 9, 32, 5, 162, DateTimeKind.Local).AddTicks(7390),
                            Amount = 6542m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 1, 28, 9, 49, 49, 523, DateTimeKind.Local).AddTicks(6057),
                            Hospital = 43,
                            InsuredId = 4,
                            MedicalCase = "Disease-33",
                            Remarks = "Remark-33",
                            TreatingDoctor = 7
                        },
                        new
                        {
                            Id = 33,
                            AdmissionDate = new DateTime(2023, 6, 28, 6, 15, 32, 221, DateTimeKind.Local).AddTicks(8076),
                            Amount = 4478m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 3, 25, 21, 20, 15, 333, DateTimeKind.Local).AddTicks(9325),
                            Hospital = 30,
                            InsuredId = 8,
                            MedicalCase = "Disease-34",
                            Remarks = "Remark-34",
                            TreatingDoctor = 3
                        },
                        new
                        {
                            Id = 34,
                            AdmissionDate = new DateTime(2023, 6, 27, 22, 39, 19, 945, DateTimeKind.Local).AddTicks(3583),
                            Amount = 2475m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 23, 16, 29, 9, 387, DateTimeKind.Local).AddTicks(4464),
                            Hospital = 13,
                            InsuredId = 4,
                            MedicalCase = "Disease-35",
                            Remarks = "Remark-35",
                            TreatingDoctor = 15
                        },
                        new
                        {
                            Id = 35,
                            AdmissionDate = new DateTime(2023, 6, 27, 13, 13, 23, 291, DateTimeKind.Local).AddTicks(5122),
                            Amount = 6827m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 6, 12, 8, 1, 59, 912, DateTimeKind.Local).AddTicks(4600),
                            Hospital = 13,
                            InsuredId = 8,
                            MedicalCase = "Disease-36",
                            Remarks = "Remark-36",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 36,
                            AdmissionDate = new DateTime(2023, 6, 28, 7, 23, 0, 710, DateTimeKind.Local).AddTicks(3209),
                            Amount = 6786m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 8, 16, 15, 29, 24, 428, DateTimeKind.Local).AddTicks(2474),
                            Hospital = 36,
                            InsuredId = 6,
                            MedicalCase = "Disease-37",
                            Remarks = "Remark-37",
                            TreatingDoctor = 4
                        },
                        new
                        {
                            Id = 37,
                            AdmissionDate = new DateTime(2023, 6, 27, 18, 4, 33, 667, DateTimeKind.Local).AddTicks(8617),
                            Amount = 3881m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 5, 12, 16, 20, 14, 699, DateTimeKind.Local).AddTicks(8767),
                            Hospital = 9,
                            InsuredId = 2,
                            MedicalCase = "Disease-38",
                            Remarks = "Remark-38",
                            TreatingDoctor = 19
                        },
                        new
                        {
                            Id = 38,
                            AdmissionDate = new DateTime(2023, 6, 28, 7, 33, 14, 686, DateTimeKind.Local).AddTicks(9573),
                            Amount = 1582m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 8, 14, 12, 53, 42, 684, DateTimeKind.Local).AddTicks(8506),
                            Hospital = 42,
                            InsuredId = 4,
                            MedicalCase = "Disease-39",
                            Remarks = "Remark-39",
                            TreatingDoctor = 10
                        },
                        new
                        {
                            Id = 39,
                            AdmissionDate = new DateTime(2023, 6, 28, 9, 57, 38, 496, DateTimeKind.Local).AddTicks(1205),
                            Amount = 3993m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 10, 5, 7, 43, 12, 807, DateTimeKind.Local).AddTicks(6663),
                            Hospital = 0,
                            InsuredId = 3,
                            MedicalCase = "Disease-40",
                            Remarks = "Remark-40",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 40,
                            AdmissionDate = new DateTime(2023, 6, 28, 1, 47, 46, 707, DateTimeKind.Local).AddTicks(3851),
                            Amount = 7093m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 12, 23, 7, 8, 49, 187, DateTimeKind.Local).AddTicks(9515),
                            Hospital = 42,
                            InsuredId = 3,
                            MedicalCase = "Disease-41",
                            Remarks = "Remark-41",
                            TreatingDoctor = 11
                        },
                        new
                        {
                            Id = 41,
                            AdmissionDate = new DateTime(2023, 6, 28, 1, 25, 41, 939, DateTimeKind.Local).AddTicks(4437),
                            Amount = 6942m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 12, 31, 13, 25, 3, 27, DateTimeKind.Local).AddTicks(8553),
                            Hospital = 5,
                            InsuredId = 3,
                            MedicalCase = "Disease-42",
                            Remarks = "Remark-42",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 42,
                            AdmissionDate = new DateTime(2023, 6, 28, 2, 13, 0, 50, DateTimeKind.Local).AddTicks(6801),
                            Amount = 9835m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 9, 26, 12, 16, 55, 491, DateTimeKind.Local).AddTicks(3002),
                            Hospital = 38,
                            InsuredId = 9,
                            MedicalCase = "Disease-43",
                            Remarks = "Remark-43",
                            TreatingDoctor = 11
                        },
                        new
                        {
                            Id = 43,
                            AdmissionDate = new DateTime(2023, 6, 28, 3, 10, 44, 674, DateTimeKind.Local).AddTicks(8234),
                            Amount = 6731m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 1, 2, 18, 46, 31, 175, DateTimeKind.Local).AddTicks(7972),
                            Hospital = 18,
                            InsuredId = 7,
                            MedicalCase = "Disease-44",
                            Remarks = "Remark-44",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 44,
                            AdmissionDate = new DateTime(2023, 6, 28, 8, 34, 1, 500, DateTimeKind.Local).AddTicks(6324),
                            Amount = 7888m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 4, 10, 21, 53, 57, 37, DateTimeKind.Local).AddTicks(779),
                            Hospital = 11,
                            InsuredId = 1,
                            MedicalCase = "Disease-45",
                            Remarks = "Remark-45",
                            TreatingDoctor = 17
                        },
                        new
                        {
                            Id = 45,
                            AdmissionDate = new DateTime(2023, 6, 28, 11, 8, 42, 349, DateTimeKind.Local).AddTicks(5839),
                            Amount = 8176m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 10, 25, 4, 45, 41, 815, DateTimeKind.Local).AddTicks(5744),
                            Hospital = 2,
                            InsuredId = 10,
                            MedicalCase = "Disease-46",
                            Remarks = "Remark-46",
                            TreatingDoctor = 4
                        },
                        new
                        {
                            Id = 46,
                            AdmissionDate = new DateTime(2023, 6, 28, 3, 40, 31, 498, DateTimeKind.Local).AddTicks(2986),
                            Amount = 4202m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 12, 26, 14, 24, 16, 767, DateTimeKind.Local).AddTicks(6733),
                            Hospital = 21,
                            InsuredId = 10,
                            MedicalCase = "Disease-47",
                            Remarks = "Remark-47",
                            TreatingDoctor = 1
                        },
                        new
                        {
                            Id = 47,
                            AdmissionDate = new DateTime(2023, 6, 27, 21, 59, 19, 748, DateTimeKind.Local).AddTicks(2638),
                            Amount = 1291m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 3, 27, 7, 50, 15, 410, DateTimeKind.Local).AddTicks(4683),
                            Hospital = 24,
                            InsuredId = 4,
                            MedicalCase = "Disease-48",
                            Remarks = "Remark-48",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 48,
                            AdmissionDate = new DateTime(2023, 6, 28, 0, 48, 23, 903, DateTimeKind.Local).AddTicks(7912),
                            Amount = 2032m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 16, 1, 8, 0, 345, DateTimeKind.Local).AddTicks(2742),
                            Hospital = 13,
                            InsuredId = 1,
                            MedicalCase = "Disease-49",
                            Remarks = "Remark-49",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 49,
                            AdmissionDate = new DateTime(2023, 6, 27, 13, 26, 45, 555, DateTimeKind.Local).AddTicks(3556),
                            Amount = 486m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 4, 20, 1, 9, 42, 210, DateTimeKind.Local).AddTicks(2794),
                            Hospital = 10,
                            InsuredId = 10,
                            MedicalCase = "Disease-50",
                            Remarks = "Remark-50",
                            TreatingDoctor = 16
                        },
                        new
                        {
                            Id = 50,
                            AdmissionDate = new DateTime(2023, 6, 28, 2, 57, 41, 475, DateTimeKind.Local).AddTicks(4448),
                            Amount = 283m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 10, 7, 30, 20, 331, DateTimeKind.Local).AddTicks(2368),
                            Hospital = 1,
                            InsuredId = 10,
                            MedicalCase = "Disease-51",
                            Remarks = "Remark-51",
                            TreatingDoctor = 10
                        },
                        new
                        {
                            Id = 51,
                            AdmissionDate = new DateTime(2023, 6, 27, 22, 45, 37, 320, DateTimeKind.Local).AddTicks(1841),
                            Amount = 6786m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 5, 5, 4, 10, 27, 461, DateTimeKind.Local).AddTicks(6088),
                            Hospital = 10,
                            InsuredId = 6,
                            MedicalCase = "Disease-52",
                            Remarks = "Remark-52",
                            TreatingDoctor = 13
                        },
                        new
                        {
                            Id = 52,
                            AdmissionDate = new DateTime(2023, 6, 28, 8, 57, 16, 168, DateTimeKind.Local).AddTicks(8291),
                            Amount = 8532m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 1, 13, 23, 41, 48, 480, DateTimeKind.Local).AddTicks(3635),
                            Hospital = 15,
                            InsuredId = 3,
                            MedicalCase = "Disease-53",
                            Remarks = "Remark-53",
                            TreatingDoctor = 19
                        },
                        new
                        {
                            Id = 53,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 39, 48, 914, DateTimeKind.Local).AddTicks(8876),
                            Amount = 3496m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 1, 23, 4, 21, 38, 258, DateTimeKind.Local).AddTicks(9550),
                            Hospital = 27,
                            InsuredId = 1,
                            MedicalCase = "Disease-54",
                            Remarks = "Remark-54",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 54,
                            AdmissionDate = new DateTime(2023, 6, 28, 4, 42, 2, 169, DateTimeKind.Local).AddTicks(1725),
                            Amount = 3921m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 8, 14, 2, 18, 11, 261, DateTimeKind.Local).AddTicks(5402),
                            Hospital = 23,
                            InsuredId = 5,
                            MedicalCase = "Disease-55",
                            Remarks = "Remark-55",
                            TreatingDoctor = 10
                        },
                        new
                        {
                            Id = 55,
                            AdmissionDate = new DateTime(2023, 6, 27, 12, 49, 59, 824, DateTimeKind.Local).AddTicks(2876),
                            Amount = 5857m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 12, 14, 4, 35, 27, 968, DateTimeKind.Local).AddTicks(3958),
                            Hospital = 29,
                            InsuredId = 2,
                            MedicalCase = "Disease-56",
                            Remarks = "Remark-56",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 56,
                            AdmissionDate = new DateTime(2023, 6, 28, 10, 6, 29, 477, DateTimeKind.Local).AddTicks(9887),
                            Amount = 4625m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 6, 9, 22, 8, 28, 513, DateTimeKind.Local).AddTicks(7573),
                            Hospital = 30,
                            InsuredId = 3,
                            MedicalCase = "Disease-57",
                            Remarks = "Remark-57",
                            TreatingDoctor = 7
                        },
                        new
                        {
                            Id = 57,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 8, 57, 258, DateTimeKind.Local).AddTicks(4178),
                            Amount = 6809m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 12, 24, 11, 52, 4, 781, DateTimeKind.Local).AddTicks(8007),
                            Hospital = 33,
                            InsuredId = 2,
                            MedicalCase = "Disease-58",
                            Remarks = "Remark-58",
                            TreatingDoctor = 2
                        },
                        new
                        {
                            Id = 58,
                            AdmissionDate = new DateTime(2023, 6, 28, 6, 29, 40, 667, DateTimeKind.Local).AddTicks(732),
                            Amount = 2127m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 4, 1, 18, 50, 0, 123, DateTimeKind.Local).AddTicks(4975),
                            Hospital = 32,
                            InsuredId = 9,
                            MedicalCase = "Disease-59",
                            Remarks = "Remark-59",
                            TreatingDoctor = 6
                        },
                        new
                        {
                            Id = 59,
                            AdmissionDate = new DateTime(2023, 6, 27, 12, 26, 22, 413, DateTimeKind.Local).AddTicks(5259),
                            Amount = 3566m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 5, 23, 5, 52, 36, 653, DateTimeKind.Local).AddTicks(1148),
                            Hospital = 40,
                            InsuredId = 10,
                            MedicalCase = "Disease-60",
                            Remarks = "Remark-60",
                            TreatingDoctor = 7
                        },
                        new
                        {
                            Id = 60,
                            AdmissionDate = new DateTime(2023, 6, 28, 7, 33, 58, 802, DateTimeKind.Local).AddTicks(9986),
                            Amount = 6854m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 8, 26, 18, 59, 35, 329, DateTimeKind.Local).AddTicks(8910),
                            Hospital = 11,
                            InsuredId = 7,
                            MedicalCase = "Disease-61",
                            Remarks = "Remark-61",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 61,
                            AdmissionDate = new DateTime(2023, 6, 28, 9, 24, 37, 61, DateTimeKind.Local).AddTicks(5044),
                            Amount = 3273m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 9, 8, 21, 4, 30, 797, DateTimeKind.Local).AddTicks(5444),
                            Hospital = 11,
                            InsuredId = 1,
                            MedicalCase = "Disease-62",
                            Remarks = "Remark-62",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 62,
                            AdmissionDate = new DateTime(2023, 6, 28, 6, 8, 30, 633, DateTimeKind.Local).AddTicks(2739),
                            Amount = 7127m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 9, 27, 8, 3, 35, 536, DateTimeKind.Local).AddTicks(5493),
                            Hospital = 0,
                            InsuredId = 5,
                            MedicalCase = "Disease-63",
                            Remarks = "Remark-63",
                            TreatingDoctor = 15
                        },
                        new
                        {
                            Id = 63,
                            AdmissionDate = new DateTime(2023, 6, 28, 6, 17, 1, 986, DateTimeKind.Local).AddTicks(7713),
                            Amount = 4620m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 6, 5, 22, 59, 23, 488, DateTimeKind.Local).AddTicks(9120),
                            Hospital = 43,
                            InsuredId = 2,
                            MedicalCase = "Disease-64",
                            Remarks = "Remark-64",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 64,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 28, 57, 978, DateTimeKind.Local).AddTicks(8389),
                            Amount = 2539m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 9, 29, 20, 42, 10, 504, DateTimeKind.Local).AddTicks(4909),
                            Hospital = 42,
                            InsuredId = 6,
                            MedicalCase = "Disease-65",
                            Remarks = "Remark-65",
                            TreatingDoctor = 13
                        },
                        new
                        {
                            Id = 65,
                            AdmissionDate = new DateTime(2023, 6, 27, 21, 16, 52, 426, DateTimeKind.Local).AddTicks(779),
                            Amount = 4550m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 2, 15, 2, 27, 15, 941, DateTimeKind.Local).AddTicks(1983),
                            Hospital = 15,
                            InsuredId = 3,
                            MedicalCase = "Disease-66",
                            Remarks = "Remark-66",
                            TreatingDoctor = 6
                        },
                        new
                        {
                            Id = 66,
                            AdmissionDate = new DateTime(2023, 6, 28, 5, 36, 22, 207, DateTimeKind.Local).AddTicks(5254),
                            Amount = 3202m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 5, 30, 17, 48, 0, 513, DateTimeKind.Local).AddTicks(5791),
                            Hospital = 5,
                            InsuredId = 1,
                            MedicalCase = "Disease-67",
                            Remarks = "Remark-67",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 67,
                            AdmissionDate = new DateTime(2023, 6, 28, 2, 24, 41, 781, DateTimeKind.Local).AddTicks(7206),
                            Amount = 506m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 1, 16, 13, 16, 29, 610, DateTimeKind.Local).AddTicks(4270),
                            Hospital = 3,
                            InsuredId = 6,
                            MedicalCase = "Disease-68",
                            Remarks = "Remark-68",
                            TreatingDoctor = 13
                        },
                        new
                        {
                            Id = 68,
                            AdmissionDate = new DateTime(2023, 6, 27, 13, 9, 11, 721, DateTimeKind.Local).AddTicks(939),
                            Amount = 2311m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 12, 31, 10, 5, 10, 106, DateTimeKind.Local).AddTicks(6000),
                            Hospital = 17,
                            InsuredId = 4,
                            MedicalCase = "Disease-69",
                            Remarks = "Remark-69",
                            TreatingDoctor = 19
                        },
                        new
                        {
                            Id = 69,
                            AdmissionDate = new DateTime(2023, 6, 27, 23, 49, 6, 213, DateTimeKind.Local).AddTicks(1674),
                            Amount = 3663m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 8, 20, 18, 44, 17, 625, DateTimeKind.Local).AddTicks(6107),
                            Hospital = 7,
                            InsuredId = 6,
                            MedicalCase = "Disease-70",
                            Remarks = "Remark-70",
                            TreatingDoctor = 6
                        },
                        new
                        {
                            Id = 70,
                            AdmissionDate = new DateTime(2023, 6, 28, 5, 34, 48, 685, DateTimeKind.Local).AddTicks(1707),
                            Amount = 2934m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 12, 1, 23, 16, 3, 139, DateTimeKind.Local).AddTicks(7705),
                            Hospital = 38,
                            InsuredId = 9,
                            MedicalCase = "Disease-71",
                            Remarks = "Remark-71",
                            TreatingDoctor = 8
                        },
                        new
                        {
                            Id = 71,
                            AdmissionDate = new DateTime(2023, 6, 28, 2, 52, 56, 789, DateTimeKind.Local).AddTicks(6017),
                            Amount = 3950m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 2, 27, 22, 39, 8, 152, DateTimeKind.Local).AddTicks(3242),
                            Hospital = 5,
                            InsuredId = 3,
                            MedicalCase = "Disease-72",
                            Remarks = "Remark-72",
                            TreatingDoctor = 0
                        },
                        new
                        {
                            Id = 72,
                            AdmissionDate = new DateTime(2023, 6, 27, 22, 40, 40, 478, DateTimeKind.Local).AddTicks(1623),
                            Amount = 4080m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 3, 18, 12, 39, 57, 182, DateTimeKind.Local).AddTicks(7963),
                            Hospital = 35,
                            InsuredId = 6,
                            MedicalCase = "Disease-73",
                            Remarks = "Remark-73",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 73,
                            AdmissionDate = new DateTime(2023, 6, 28, 0, 20, 34, 816, DateTimeKind.Local).AddTicks(2141),
                            Amount = 7481m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 2, 12, 22, 10, 52, 521, DateTimeKind.Local).AddTicks(8084),
                            Hospital = 44,
                            InsuredId = 8,
                            MedicalCase = "Disease-74",
                            Remarks = "Remark-74",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 74,
                            AdmissionDate = new DateTime(2023, 6, 27, 14, 59, 52, 186, DateTimeKind.Local).AddTicks(6703),
                            Amount = 2909m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 1, 10, 12, 3, 35, 573, DateTimeKind.Local).AddTicks(3049),
                            Hospital = 30,
                            InsuredId = 9,
                            MedicalCase = "Disease-75",
                            Remarks = "Remark-75",
                            TreatingDoctor = 3
                        },
                        new
                        {
                            Id = 75,
                            AdmissionDate = new DateTime(2023, 6, 27, 21, 46, 30, 464, DateTimeKind.Local).AddTicks(900),
                            Amount = 4111m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 8, 5, 8, 1, 19, 418, DateTimeKind.Local).AddTicks(4740),
                            Hospital = 42,
                            InsuredId = 4,
                            MedicalCase = "Disease-76",
                            Remarks = "Remark-76",
                            TreatingDoctor = 12
                        },
                        new
                        {
                            Id = 76,
                            AdmissionDate = new DateTime(2023, 6, 28, 0, 25, 10, 386, DateTimeKind.Local).AddTicks(1021),
                            Amount = 6801m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 13, 9, 43, 276, DateTimeKind.Local).AddTicks(9407),
                            Hospital = 34,
                            InsuredId = 2,
                            MedicalCase = "Disease-77",
                            Remarks = "Remark-77",
                            TreatingDoctor = 6
                        },
                        new
                        {
                            Id = 77,
                            AdmissionDate = new DateTime(2023, 6, 27, 20, 32, 33, 99, DateTimeKind.Local).AddTicks(3879),
                            Amount = 7194m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 10, 2, 9, 33, 20, 372, DateTimeKind.Local).AddTicks(5315),
                            Hospital = 40,
                            InsuredId = 6,
                            MedicalCase = "Disease-78",
                            Remarks = "Remark-78",
                            TreatingDoctor = 13
                        },
                        new
                        {
                            Id = 78,
                            AdmissionDate = new DateTime(2023, 6, 27, 22, 39, 46, 750, DateTimeKind.Local).AddTicks(1131),
                            Amount = 3162m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 5, 24, 2, 59, 47, 493, DateTimeKind.Local).AddTicks(240),
                            Hospital = 40,
                            InsuredId = 6,
                            MedicalCase = "Disease-79",
                            Remarks = "Remark-79",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 79,
                            AdmissionDate = new DateTime(2023, 6, 27, 23, 14, 18, 640, DateTimeKind.Local).AddTicks(7636),
                            Amount = 2618m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 9, 13, 19, 45, 32, 635, DateTimeKind.Local).AddTicks(2130),
                            Hospital = 4,
                            InsuredId = 6,
                            MedicalCase = "Disease-80",
                            Remarks = "Remark-80",
                            TreatingDoctor = 5
                        },
                        new
                        {
                            Id = 80,
                            AdmissionDate = new DateTime(2023, 6, 28, 9, 51, 54, 570, DateTimeKind.Local).AddTicks(8131),
                            Amount = 9938m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 7, 31, 3, 3, 26, 256, DateTimeKind.Local).AddTicks(5050),
                            Hospital = 24,
                            InsuredId = 5,
                            MedicalCase = "Disease-81",
                            Remarks = "Remark-81",
                            TreatingDoctor = 13
                        },
                        new
                        {
                            Id = 81,
                            AdmissionDate = new DateTime(2023, 6, 27, 12, 15, 4, 168, DateTimeKind.Local).AddTicks(3803),
                            Amount = 5310m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 7, 9, 2, 46, 31, 838, DateTimeKind.Local).AddTicks(1555),
                            Hospital = 12,
                            InsuredId = 5,
                            MedicalCase = "Disease-82",
                            Remarks = "Remark-82",
                            TreatingDoctor = 3
                        },
                        new
                        {
                            Id = 82,
                            AdmissionDate = new DateTime(2023, 6, 28, 8, 14, 14, 547, DateTimeKind.Local).AddTicks(4623),
                            Amount = 627m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 5, 1, 4, 40, 34, 901, DateTimeKind.Local).AddTicks(7720),
                            Hospital = 31,
                            InsuredId = 1,
                            MedicalCase = "Disease-83",
                            Remarks = "Remark-83",
                            TreatingDoctor = 1
                        },
                        new
                        {
                            Id = 83,
                            AdmissionDate = new DateTime(2023, 6, 27, 20, 48, 4, 994, DateTimeKind.Local).AddTicks(2148),
                            Amount = 2713m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 6, 30, 23, 43, 0, 137, DateTimeKind.Local).AddTicks(1433),
                            Hospital = 45,
                            InsuredId = 6,
                            MedicalCase = "Disease-84",
                            Remarks = "Remark-84",
                            TreatingDoctor = 0
                        },
                        new
                        {
                            Id = 84,
                            AdmissionDate = new DateTime(2023, 6, 28, 2, 4, 36, 564, DateTimeKind.Local).AddTicks(1335),
                            Amount = 7223m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 6, 21, 21, 8, 43, 655, DateTimeKind.Local).AddTicks(1146),
                            Hospital = 15,
                            InsuredId = 1,
                            MedicalCase = "Disease-85",
                            Remarks = "Remark-85",
                            TreatingDoctor = 18
                        },
                        new
                        {
                            Id = 85,
                            AdmissionDate = new DateTime(2023, 6, 27, 20, 28, 58, 127, DateTimeKind.Local).AddTicks(1974),
                            Amount = 5708m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 9, 11, 1, 51, 7, 51, DateTimeKind.Local).AddTicks(258),
                            Hospital = 34,
                            InsuredId = 10,
                            MedicalCase = "Disease-86",
                            Remarks = "Remark-86",
                            TreatingDoctor = 4
                        },
                        new
                        {
                            Id = 86,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 28, 51, 364, DateTimeKind.Local).AddTicks(3158),
                            Amount = 1390m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 4, 26, 5, 10, 11, 285, DateTimeKind.Local).AddTicks(4530),
                            Hospital = 30,
                            InsuredId = 9,
                            MedicalCase = "Disease-87",
                            Remarks = "Remark-87",
                            TreatingDoctor = 16
                        },
                        new
                        {
                            Id = 87,
                            AdmissionDate = new DateTime(2023, 6, 27, 12, 13, 59, 116, DateTimeKind.Local).AddTicks(1225),
                            Amount = 2755m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 8, 22, 4, 15, 23, 505, DateTimeKind.Local).AddTicks(9950),
                            Hospital = 35,
                            InsuredId = 10,
                            MedicalCase = "Disease-88",
                            Remarks = "Remark-88",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 88,
                            AdmissionDate = new DateTime(2023, 6, 27, 19, 40, 4, 435, DateTimeKind.Local).AddTicks(3200),
                            Amount = 3524m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 2, 11, 20, 14, 28, 306, DateTimeKind.Local).AddTicks(143),
                            Hospital = 41,
                            InsuredId = 7,
                            MedicalCase = "Disease-89",
                            Remarks = "Remark-89",
                            TreatingDoctor = 16
                        },
                        new
                        {
                            Id = 89,
                            AdmissionDate = new DateTime(2023, 6, 27, 18, 48, 9, 123, DateTimeKind.Local).AddTicks(1690),
                            Amount = 7925m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 10, 23, 13, 16, 22, 113, DateTimeKind.Local).AddTicks(963),
                            Hospital = 30,
                            InsuredId = 1,
                            MedicalCase = "Disease-90",
                            Remarks = "Remark-90",
                            TreatingDoctor = 14
                        },
                        new
                        {
                            Id = 90,
                            AdmissionDate = new DateTime(2023, 6, 28, 10, 21, 14, 53, DateTimeKind.Local).AddTicks(1589),
                            Amount = 6877m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 4, 15, 6, 30, 5, 585, DateTimeKind.Local).AddTicks(2260),
                            Hospital = 9,
                            InsuredId = 7,
                            MedicalCase = "Disease-91",
                            Remarks = "Remark-91",
                            TreatingDoctor = 1
                        },
                        new
                        {
                            Id = 91,
                            AdmissionDate = new DateTime(2023, 6, 27, 15, 7, 21, 490, DateTimeKind.Local).AddTicks(1066),
                            Amount = 932m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 5, 29, 6, 33, 15, 344, DateTimeKind.Local).AddTicks(4342),
                            Hospital = 27,
                            InsuredId = 4,
                            MedicalCase = "Disease-92",
                            Remarks = "Remark-92",
                            TreatingDoctor = 19
                        },
                        new
                        {
                            Id = 92,
                            AdmissionDate = new DateTime(2023, 6, 27, 20, 41, 29, 749, DateTimeKind.Local).AddTicks(7788),
                            Amount = 1242m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2023, 3, 22, 22, 0, 31, 744, DateTimeKind.Local).AddTicks(3108),
                            Hospital = 20,
                            InsuredId = 10,
                            MedicalCase = "Disease-93",
                            Remarks = "Remark-93",
                            TreatingDoctor = 8
                        },
                        new
                        {
                            Id = 93,
                            AdmissionDate = new DateTime(2023, 6, 27, 23, 50, 6, 164, DateTimeKind.Local).AddTicks(4593),
                            Amount = 9213m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 16, 8, 8, 44, 207, DateTimeKind.Local).AddTicks(7266),
                            Hospital = 19,
                            InsuredId = 1,
                            MedicalCase = "Disease-94",
                            Remarks = "Remark-94",
                            TreatingDoctor = 1
                        },
                        new
                        {
                            Id = 94,
                            AdmissionDate = new DateTime(2023, 6, 27, 15, 14, 15, 14, DateTimeKind.Local).AddTicks(4130),
                            Amount = 8287m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 3, 23, 0, 46, 30, 745, DateTimeKind.Local).AddTicks(8788),
                            Hospital = 26,
                            InsuredId = 7,
                            MedicalCase = "Disease-95",
                            Remarks = "Remark-95",
                            TreatingDoctor = 9
                        },
                        new
                        {
                            Id = 95,
                            AdmissionDate = new DateTime(2023, 6, 28, 4, 38, 11, 71, DateTimeKind.Local).AddTicks(3689),
                            Amount = 6276m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 3, 29, 3, 26, 21, 101, DateTimeKind.Local).AddTicks(8468),
                            Hospital = 0,
                            InsuredId = 5,
                            MedicalCase = "Disease-96",
                            Remarks = "Remark-96",
                            TreatingDoctor = 16
                        },
                        new
                        {
                            Id = 96,
                            AdmissionDate = new DateTime(2023, 6, 27, 17, 21, 6, 990, DateTimeKind.Local).AddTicks(5431),
                            Amount = 9936m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2023, 6, 9, 3, 18, 46, 534, DateTimeKind.Local).AddTicks(1263),
                            Hospital = 19,
                            InsuredId = 9,
                            MedicalCase = "Disease-97",
                            Remarks = "Remark-97",
                            TreatingDoctor = 17
                        },
                        new
                        {
                            Id = 97,
                            AdmissionDate = new DateTime(2023, 6, 28, 1, 37, 49, 809, DateTimeKind.Local).AddTicks(2566),
                            Amount = 7700m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 11, 30, 14, 10, 57, 97, DateTimeKind.Local).AddTicks(2724),
                            Hospital = 11,
                            InsuredId = 10,
                            MedicalCase = "Disease-98",
                            Remarks = "Remark-98",
                            TreatingDoctor = 7
                        },
                        new
                        {
                            Id = 98,
                            AdmissionDate = new DateTime(2023, 6, 28, 10, 25, 34, 261, DateTimeKind.Local).AddTicks(4397),
                            Amount = 6776m,
                            ClaimStatus = 0,
                            CreatedDate = new DateTime(2022, 10, 21, 3, 9, 21, 410, DateTimeKind.Local).AddTicks(6452),
                            Hospital = 37,
                            InsuredId = 6,
                            MedicalCase = "Disease-99",
                            Remarks = "Remark-99",
                            TreatingDoctor = 15
                        },
                        new
                        {
                            Id = 99,
                            AdmissionDate = new DateTime(2023, 6, 28, 4, 11, 44, 239, DateTimeKind.Local).AddTicks(2535),
                            Amount = 1173m,
                            ClaimStatus = 2,
                            CreatedDate = new DateTime(2022, 10, 16, 10, 59, 56, 391, DateTimeKind.Local).AddTicks(1495),
                            Hospital = 38,
                            InsuredId = 5,
                            MedicalCase = "Disease-100",
                            Remarks = "Remark-100",
                            TreatingDoctor = 4
                        },
                        new
                        {
                            Id = 100,
                            AdmissionDate = new DateTime(2023, 6, 28, 6, 41, 37, 733, DateTimeKind.Local).AddTicks(4066),
                            Amount = 9572m,
                            ClaimStatus = 1,
                            CreatedDate = new DateTime(2022, 12, 9, 18, 27, 55, 293, DateTimeKind.Local).AddTicks(9905),
                            Hospital = 7,
                            InsuredId = 2,
                            MedicalCase = "Disease-101",
                            Remarks = "Remark-101",
                            TreatingDoctor = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Insured", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("InsuredName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.ToTable("Insured");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNumber = "VC4dNg7UkXwQQMDT",
                            CreatedDate = new DateTime(2023, 6, 7, 9, 4, 55, 344, DateTimeKind.Local).AddTicks(3179),
                            DateOfBirth = new DateTime(1974, 5, 13, 8, 30, 11, 857, DateTimeKind.Local).AddTicks(3413),
                            Gender = 1,
                            InsuredName = "Ben White"
                        },
                        new
                        {
                            Id = 2,
                            CardNumber = "OHybnfk7frvyXngW",
                            CreatedDate = new DateTime(2023, 5, 12, 19, 11, 25, 251, DateTimeKind.Local).AddTicks(2904),
                            DateOfBirth = new DateTime(1990, 10, 15, 1, 44, 37, 820, DateTimeKind.Local).AddTicks(3662),
                            Gender = 1,
                            InsuredName = "Bethany Mertz"
                        },
                        new
                        {
                            Id = 3,
                            CardNumber = "8SvgeEvU073lYRTt",
                            CreatedDate = new DateTime(2023, 6, 23, 19, 30, 22, 254, DateTimeKind.Local).AddTicks(9084),
                            DateOfBirth = new DateTime(1999, 3, 29, 15, 2, 46, 132, DateTimeKind.Local).AddTicks(4536),
                            Gender = 2,
                            InsuredName = "Tony Cassin"
                        },
                        new
                        {
                            Id = 4,
                            CardNumber = "ULaWAFDxTRNpwIgC",
                            CreatedDate = new DateTime(2023, 5, 2, 2, 27, 19, 452, DateTimeKind.Local).AddTicks(8339),
                            DateOfBirth = new DateTime(1956, 10, 1, 9, 13, 16, 902, DateTimeKind.Local).AddTicks(8584),
                            Gender = 1,
                            InsuredName = "Cora Towne"
                        },
                        new
                        {
                            Id = 5,
                            CardNumber = "XbPzzQloDGrRnyTL",
                            CreatedDate = new DateTime(2022, 10, 3, 11, 49, 18, 454, DateTimeKind.Local).AddTicks(5608),
                            DateOfBirth = new DateTime(1969, 7, 25, 12, 11, 4, 713, DateTimeKind.Local).AddTicks(2715),
                            Gender = 2,
                            InsuredName = "Nicole Vandervort"
                        },
                        new
                        {
                            Id = 6,
                            CardNumber = "O1uq3zwUI2M9ELdK",
                            CreatedDate = new DateTime(2022, 9, 27, 16, 16, 19, 846, DateTimeKind.Local).AddTicks(8001),
                            DateOfBirth = new DateTime(1954, 1, 30, 12, 47, 29, 859, DateTimeKind.Local).AddTicks(8909),
                            Gender = 2,
                            InsuredName = "Vera Becker"
                        },
                        new
                        {
                            Id = 7,
                            CardNumber = "d9eps2pNx6UE56zF",
                            CreatedDate = new DateTime(2023, 5, 15, 8, 49, 30, 325, DateTimeKind.Local).AddTicks(2545),
                            DateOfBirth = new DateTime(1972, 12, 6, 0, 41, 55, 43, DateTimeKind.Local).AddTicks(4364),
                            Gender = 1,
                            InsuredName = "Nina Grimes"
                        },
                        new
                        {
                            Id = 8,
                            CardNumber = "QfSzyt2NGjveB7Wp",
                            CreatedDate = new DateTime(2023, 2, 22, 23, 14, 58, 836, DateTimeKind.Local).AddTicks(3615),
                            DateOfBirth = new DateTime(1992, 2, 3, 16, 7, 3, 679, DateTimeKind.Local).AddTicks(7752),
                            Gender = 1,
                            InsuredName = "Carlos Gulgowski"
                        },
                        new
                        {
                            Id = 9,
                            CardNumber = "fr6Xnxt2XEnqw3lR",
                            CreatedDate = new DateTime(2023, 5, 4, 15, 15, 58, 153, DateTimeKind.Local).AddTicks(1003),
                            DateOfBirth = new DateTime(1979, 3, 10, 1, 35, 38, 564, DateTimeKind.Local).AddTicks(2097),
                            Gender = 2,
                            InsuredName = "Veronica Mante"
                        },
                        new
                        {
                            Id = 10,
                            CardNumber = "ie17ANhTCj5vhcu9",
                            CreatedDate = new DateTime(2023, 6, 28, 10, 44, 42, 939, DateTimeKind.Local).AddTicks(5972),
                            DateOfBirth = new DateTime(1995, 4, 18, 5, 41, 3, 900, DateTimeKind.Local).AddTicks(4045),
                            Gender = 1,
                            InsuredName = "Priscilla Weber"
                        });
                });

            modelBuilder.Entity("Domain.Models.Claim", b =>
                {
                    b.HasOne("Domain.Models.Insured", "Insured")
                        .WithMany()
                        .HasForeignKey("InsuredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insured");
                });
#pragma warning restore 612, 618
        }
    }
}
